@startuml

class Main{
}

package model {
  
package Cinema{
  
class cinema{
  - ticket_counter: TicketCounter
  - user: User
}

  package Ticket{
    class TicketCounter {
      - customers: Customers
      - register: TicketRegister
    }

    class Ticket {
      + title: String
      + screening_time: Datetime
      + price: Integer
      + price_type: PriceGradeType
    }
  }

  package TicketType {
    class TicketTypeFactory{
      create(Customer): PriceGradeClass
    }
    class CinemaCitizen {
      + price: Integer
      + name: String
      + initialize(timezone)
    }
    class CinemaCitizenSenior {
      + price: Integer
      + name: String
      + initialize(timezone)
    }
    class Ordinary {
      + price: Integer
      + name: String
      + initialize(timezone)
    }
    class Senior {
      + price: Integer
      + name: String
      + initialize(timezone)
    }
    class CollegeStudent {
      + price: Integer
      + name: String
      + initialize(timezone)
    }
    class HighSchoolStudent {
      + price: Integer
      + name: String
      + initialize(timezone)
    }
    class ElementarySchoolStudent {
      + price: Integer
      + name: String
      + initialize(timezone)
    }
    class Handicapped {
      + price: Integer
      + name: String
      + initialize(timezone)
    }
    class HandicappedHighSchool {
      + price: Integer
      + name: String
      + initialize(timezone)
    }
  }

  package DateTime{
    class CinemaTime {
      + time_division: TimeZone
    }

    enum TimeZone {
      WEEKDAY_DAYTIME
      WEEKDAY_NIGHTTIME
      HOLIDAY_DAYTIME
      HOLIDAY_NIGHTTIME
      CINEMA_DAY
    }
  }
}
}

@enduml 